### ISSUE TITLE
Emit row on field edit?

### ISSUE THREAD

**Issue by johndparker** [Gippsman2017/node-red-node-ui-etable#4]
I see that ui-etable emits the table row when I click on it, but is it possible to emit the row when an edit is completed?

Many thanks for a great node!

John

**Comment by johndparker** [comment]
I see that others have asked similar questions, but even with the example flow I do not see any output when a field is updated.

Thanks

John

**Comment by johndparker** [comment]
Not to worry - figured it out - tweaked the callback to do what I need. 
If I get time I'll fork and attempt to make it optional.

Thanks

John

**Comment by Gippsman2017** [comment]
Hi John, 

Send me the fix and I will add it etc. 

If you have a
demo flow, then I will check it out 

Cheers 

On 2020-01-05 20:04,
johndparker wrote: 

> Not to worry - figured it out - tweaked the
callback to do what I need.
> If I get time I'll fork and attempt to
make it optional. 
> 
> Thanks 
> 
> John 
> 
> --
> You are receiving
this because you are subscribed to this thread.
> Reply to this email
directly, view it on GitHub [1], or unsubscribe [2].
!DSPAM:5e11a68f192388204214881!

 

Links:
------
[1]
https://github.com/Gippsman2017/node-red-node-ui-etable/issues/4?email_source=notifications&amp;email_token=AGELCQ7LYWPNNF2ZRWPPMB3Q4GPANA5CNFSM4KCVRKXKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEIDRYYI#issuecomment-570891361
[2]
